services:

  db_tasty:
    image: postgres:alpine
    environment:
      POSTGRES_USER: jasko
      POSTGRES_DB: db_tasty
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-tasty:
    restart: unless-stopped
    build: .
    depends_on:
      - db_tasty
    environment:
      # Use nomes que o Spring Boot reconhece nativamente
      GROK.API.KEY: ${GROK_TOKEN}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_tasty:5432/db_tasty
      SPRING_DATASOURCE_USERNAME: jasko
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - default
      - proxy

volumes:
  pgdata:

networks:
  proxy:
    external: true